name: CI for releases

on:
  push:
    tags:
      - 'v*' # Triggers only if a tag starting with a v is created (e.g. v1.1.2)

jobs:
  build-and-push-docker-image: # This workflow build a docker image of the project, create an image on ghcr.io and publish a release to the repository
    runs-on: ubuntu-latest
    permissions:
      contents: write # github.com/dustin-ward/AdventOfCodeDiscord/releases
      packages: write # ghcr.io/dustin-ward/AdventOfCodeDiscord/:latest
    env:
      IMAGE_NAME: "advent-of-code-discord" # can't contain uppercases
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/${{ github.sha }}/README.md
      -
        name: Github Automatic Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
